#!/bin/bash
# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME" || exit

# Retreives the home folder
echo "Init submodules"
yadm submodule update --recursive --init
yadm submodule foreach git checkout master
yadm submodule foreach git pull
