CompileFlags:
  Add: [-Wall, -Wextra, -Wno-unknown-warning-option, -std=c++23]
  Remove: [-mcall-prologues, -fmodules-ts, -fmodule-mapper=*, -fdeps-format=p1689r5,
           -mlongcalls, -mdisable-hardware-atomics, -fstrict-volatile-bitfields,
           -fno-tree-switch-conversion]
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict
  Includes:
    IgnoreHeader:
        - "Eigen/src/.*\\.h"
        - "H5*public.h"
        - "xtensor/xtensor_forward.hpp"
        - "xtensor/xslice.hpp"
        - "experimental/bits/.*"
  Suppress: 'pp_including_mainfile_in_preamble'
  ClangTidy:
    FastCheckFilter: Loose
    Add:
      - bugprone-*
      - llvm-*
      - modernize-*
      - mpi-*
      - openmp-*
      - performance-*
      - readability-*
    Remove:
      - readability-identifier-length
      - readability-magic-numbers
      - cppcoreguidelines-non-private-member-variables-in-classes
    CheckOptions:
      readability-identifier-naming.ClassIgnoredRegex: ".*_[vt]$"
      readability-identifier-naming.VariableCase: lower_case
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.ClassMemberCase: lower_case
      readability-identifier-naming.ClassMethodCase: camelBack
      readability-identifier-naming.MacroDefinitionCase: UPPER_CASE
      cppcoreguidelines-macro-usage.CheckCapsOnly: true
      cppcoreguidelines-avoid-do-while.IgnoreMacros: true
